# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Online presence # ex. I m Chuan
name: Ifunanya Ikemma # ex. DONGChuan
email: ifunanyaikemma@gmail.com
location: Enugu # ex. Nice, France
company: University
company_url: iphytech.me
github_url: https://github.com/Iphytech # ex. https://github.com/DONGChuan
github_username: Iphytech # ex. DONGChuan
description: My page
favicon: favicon.png # Image must be in assets/images
repository: Iphytech/Iphytech.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://Iphytech.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: https://iphytech.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
provider : google
google :
tracking_id : 'UA-110059927-1'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [C++ Python, MySQL, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, VueJS, NodeJS, ExpressJS, MongoDB, PHP, Material design, Bulma, Boostrap]
skill_mobile_app_keywords: [ Sketch UI Desgin]
